interface Faq {
  question: string;
  answer: string;
}

const FAQS: Faq[] = [
  {
    question: "What does this actually do?",
    answer:
      "Upload an audio or video recording and get a real transcript, a summary, and action items — generated by Google's Gemini API, not mocked. Ask Fathom, built into every call, answers questions using that call's actual transcript.",
  },
  {
    question: "What's free?",
    answer:
      "Everything that works today: uploading (up to 200 MB or 30 minutes per recording), transcripts, summaries, action items, Ask Fathom, playlists, and a shareable link for every recording. The Pro and Plus tiers shown on Pricing are for reference — they aren't real subscriptions yet.",
  },
  {
    question: "What's real, and what's just a placeholder?",
    answer:
      "My Calls, Upload, a meeting's own page, Ask Fathom, Playlists, share links, and real accounts (email/password or Google) are all fully built. Team Calls, Alerts, and Deals are honest stubs — they describe what they'd do but don't do it. There's no bot that joins a live Zoom, Meet, or Teams call; you upload a recording after the fact.",
  },
  {
    question: "Is my recording stored, and where?",
    answer:
      "Yes. The recording file is stored in Vercel Blob. When it's processed, a temporary copy is sent to Google's Gemini API to generate the transcript and summary; Google automatically deletes files uploaded to Gemini within 48 hours. The transcript, summary, and action items produced from it are stored in MongoDB, tied to your account.",
  },
  {
    question: "Do I need an account to watch a shared recording?",
    answer:
      "No — anyone with a recording's share link can view it, no login required. An account is only needed to upload your own recordings and manage your own My Calls and Playlists.",
  },
  {
    question: "Can I delete something I've uploaded?",
    answer:
      "Yes, at any time, from My Calls or Playlists. Deleting a recording removes its stored file and turns its share link off immediately.",
  },
];

/** A static Q&A list — no accordion, since the landing page is fully prerendered and doesn't need client JS for this. */
export function LandingFAQ() {
  return (
    <section id="faq" className="mx-auto max-w-3xl scroll-mt-8 px-4 pb-20 sm:px-6">
      <h2 className="text-center text-3xl font-bold tracking-tight sm:text-4xl">Frequently asked questions.</h2>
      <dl className="mt-10 divide-y divide-[#2B241C]/10 dark:divide-[#F2EDDD]/10">
        {FAQS.map((faq) => (
          <div key={faq.question} className="py-6 first:pt-0">
            <dt className="text-base font-bold">{faq.question}</dt>
            <dd className="mt-2 text-sm leading-relaxed text-[#2B241C]/70 dark:text-[#F2EDDD]/70">{faq.answer}</dd>
          </div>
        ))}
      </dl>
    </section>
  );
}
