"use client";

import { useState } from "react";
import { ChevronDownIcon } from "@/components/ui/icons";

interface Faq {
  question: string;
  answer: string;
}

const FAQS: Faq[] = [
  {
    question: "What does this actually do?",
    answer:
      "Upload an audio or video recording and get a real transcript, a summary, and action items — generated by Google's Gemini API, not mocked. Ask Fathom, built into every call, answers questions using that call's actual transcript.",
  },
  {
    question: "What's free?",
    answer:
      "Everything that works today: uploading (up to 200 MB or 30 minutes per recording), transcripts, summaries, action items, Ask Fathom, playlists, and a shareable link for every recording. The Pro and Plus tiers shown on Pricing are for reference — they aren't real subscriptions yet.",
  },
  {
    question: "What's real, and what's just a placeholder?",
    answer:
      "My Calls, Upload, a meeting's own page, Ask Fathom, Playlists, share links, and real accounts (email/password or Google) are all fully built. Team Calls, Alerts, and Deals are honest stubs — they describe what they'd do but don't do it. There's no bot that joins a live Zoom, Meet, or Teams call; you upload a recording after the fact.",
  },
  {
    question: "Is my recording stored, and where?",
    answer:
      "Yes. The recording file is stored in Vercel Blob. When it's processed, a temporary copy is sent to Google's Gemini API to generate the transcript and summary; Google automatically deletes files uploaded to Gemini within 48 hours. The transcript, summary, and action items produced from it are stored in MongoDB, tied to your account.",
  },
  {
    question: "Do I need an account to watch a shared recording?",
    answer:
      "No — anyone with a recording's share link can view it, no login required. An account is only needed to upload your own recordings and manage your own My Calls and Playlists.",
  },
  {
    question: "Can I delete something I've uploaded?",
    answer:
      "Yes, at any time, from My Calls or Playlists. Deleting a recording removes its stored file and turns its share link off immediately.",
  },
];

/** A single question: its own bordered box, collapsed until clicked, with a chevron that flips to show state. */
function FaqRow({ faq, open, onToggle }: { faq: Faq; open: boolean; onToggle: () => void }) {
  return (
    <div className="rounded-2xl border border-[#2B241C]/15 dark:border-[#F2EDDD]/15">
      <button
        type="button"
        onClick={onToggle}
        aria-expanded={open}
        className="flex w-full items-center justify-between gap-4 px-5 py-4 text-left text-base font-bold focus-visible:outline-2 focus-visible:outline-offset-[-2px] focus-visible:outline-[#0F6E56] dark:focus-visible:outline-[#3EC79A]"
      >
        {faq.question}
        <ChevronDownIcon
          className={`h-5 w-5 shrink-0 text-[#2B241C]/50 transition-transform duration-200 dark:text-[#F2EDDD]/50 ${open ? "rotate-180" : ""}`}
        />
      </button>
      {open && (
        <p className="px-5 pb-5 text-sm leading-relaxed text-[#2B241C]/70 dark:text-[#F2EDDD]/70">{faq.answer}</p>
      )}
    </div>
  );
}

/** An accordion: one question open at a time, collapsed by default — the standard FAQ pattern. */
export function LandingFAQ() {
  const [openIndex, setOpenIndex] = useState<number | null>(null);

  return (
    <section id="faq" className="mx-auto max-w-3xl scroll-mt-8 px-4 pb-20 sm:px-6">
      <h2 className="text-center text-3xl font-bold tracking-tight sm:text-4xl">Frequently asked questions.</h2>
      <div className="mt-10 space-y-3">
        {FAQS.map((faq, i) => (
          <FaqRow key={faq.question} faq={faq} open={openIndex === i} onToggle={() => setOpenIndex(openIndex === i ? null : i)} />
        ))}
      </div>
    </section>
  );
}
